backend:
  name: github
  site_domain: netlify-test.w3bmix.ibm.com
  repo: cal-design/cms-boilerplate
  branch: master
  api_root: https://github.ibm.com/api/v3
  site_id: netlify-test.w3bmix.ibm.com
  base_url: https://netlify-auth.w3bmix.ibm.com

media_folder: "assets/img/uploads" # Media files will be stored in the repo under images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "designer" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Designer Doc Page" # Used in the UI, ie.: "New Post"
    folder: "design" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "Excerpt", widget: "text"}
      - {label: "List Position", name: "order", widget: "number"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "developer" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Developer Doc Page" # Used in the UI, ie.: "New Post"
    folder: "dev" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "Excerpt", widget: "text"}
      - {label: "List Position", name: "order", widget: "number"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "author" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Author Doc Page" # Used in the UI, ie.: "New Post"
    folder: "author" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "Excerpt", widget: "text"}
      - {label: "List Position", name: "order", widget: "number"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
